[@b.head/]
[@b.toolbar title="新增、修改学生信息"]
	bar.addBack();
[/@]

[@b.form action="!save" name="exchangeForm" theme="list"]
   [@b.textfield name="exchange.code" label="学号" value=(exchange.code)! check="maxLength(100)" required="true" /]
   [@b.textfield name="exchange.name" label="姓名" value=(exchange.name)! check="maxLength(100)" required="true" /]
   [@b.select name="exchange.gender.id" label="性别" value=(exchange.gender)!  required="true" items=genders/]
   [@b.datepicker name="exchange.birthday" label="出生日期" value=(exchange.birthday)! required="false"/]
   [@b.textfield name="exchange.college" label="院系" value=(exchange.college)! check="maxLength(100)" required="false"/]
   [@b.textfield name="exchange.major" label="专业" value=(exchange.major)! check="maxLength(100)" required="false"/]
   [@b.textfield name="exchange.email" label="邮箱" value=(exchange.email)! check="match('email').maxLength(100)" required="false"/]
   [@b.textfield name="exchange.tel" label="联系电话" value=(exchange.tel)! check="maxLength(100)" required="false"/]
   [@b.textfield name="exchange.fgnschool" label="国外院校" value=(exchange.fgnschool)! check="maxLength(100)" required="false"/]
   [@b.textfield name="exchange.outtime" label="出国时间段" value=(exchange.outtime)! check="maxLength(100)" required="false"/]
   [@b.select name="exchange.stdtypes.id" label="学生类别" value=(exchange.stdtypes)!  required="true"  items=stdtypes/]
   [@b.textfield name="exchange.supported" label="资助情况" value=(exchange.supported)! check="maxLength(100)" required="false"/]
   [@b.textfield name="exchange.notes" label="备注" value=(exchange.notes)! check="maxLength(100)" required="false"/]
   [@b.formfoot]
		[@b.submit value="提交" class="btn btn-default"/]
		<input type="hidden" name="exchange.id" value="${(exchange.id)!}"/>
   [/@]
[/@]
[@b.foot/]